### PR TITLE
Ignore - just testing how GH actions work

### PR DESCRIPTION
**Pull request by adcroft**
Really liking GitHub actions btw.

### CODE REVIEW

**Comment by adcroft** [comment]
Nothing happened! I wonder if this is a security feature so you can't mess with the tests until they are merged.

**Comment by marshallward** [comment]
Maybe I need to enable it somehow.

**Comment by marshallward** [comment]
Looks like I have "Allow all actions" enabled, so that is not the reason.

**Comment by marshallward** [comment]
Maybe my "main" branch needs to have it already?

**Comment by adcroft** [comment]
That's my guess too.

**Pull request closed without merging**
